apiVersion: v1
kind: Service
metadata: { name: api }
spec:
  image: local://demo@v1
  replicas: 3
  env:
    - { name: HEALTHY, value: "1" }
  readinessProbe:
    httpGet: { path: /healthz }
    initialDelaySeconds: 1
    periodSeconds: 2
    failureThreshold: 3
  livenessProbe:
    httpGet: { path: /livez }
    initialDelaySeconds: 1
    periodSeconds: 2
    failureThreshold: 3
  rollout:
    strategy: BlueGreen
